version: '3'

services:
    db:
        image: postgres
    django:
        build: .
        command: gunicorn sao-case-management.wsgi:application --bind 0.0.0.0:8000 --workers 3
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
