# Generated by Django 2.0.3 on 2018-03-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_short_description', models.CharField(max_length=200)),
                ('open_date', models.DateTimeField(verbose_name='date case was opened')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divison', models.CharField(choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], default='ACA', max_length=3)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='caseworkers',
            field=models.ManyToManyField(to='cases.Person'),
        ),
    ]
