# Generated by Django 2.0.6 on 2018-08-27 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import phonenumber_field.modelfields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('client_SID', models.CharField(blank=True, max_length=10)),
                ('incident_description', tinymce.models.HTMLField()),
                ('open_date', models.DateField(default=django.utils.timezone.now, verbose_name='date case was opened')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='date case was closed')),
                ('divisions', multiselectfield.db.fields.MultiSelectField(choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], max_length=15)),
                ('is_open', models.BooleanField(default=True, verbose_name='case open?')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='time since last update')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_description', tinymce.models.HTMLField()),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Case')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('division', models.CharField(choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], default='ACA', max_length=3)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caseworker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caseworker',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='caseworkers',
            field=models.ManyToManyField(blank=True, to='cases.Person'),
        ),
        migrations.AddField(
            model_name='case',
            name='intake_caseworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='cases.Person'),
        ),
    ]
