# Generated by Django 2.0.3 on 2018-03-29 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='divison',
            new_name='division',
        ),
    ]
