# Generated by Django 2.0.3 on 2018-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='close_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date case was closed'),
        ),
    ]
