# Generated by Django 2.0.3 on 2018-03-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180329_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseworkers',
        ),
        migrations.AddField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cases.Person'),
        ),
        migrations.AddField(
            model_name='case',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
