# Generated by Django 2.0.3 on 2018-03-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180330_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caseworker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Person'),
        ),
    ]
