# Generated by Django 2.1.3 on 2018-11-18 03:11

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_caseupdate_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='open_date',
            field=models.DateField(default=cases.models.get_current_date, verbose_name='date case was opened'),
        ),
    ]
