# Generated by Django 2.0.3 on 2018-03-29 07:20

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20180329_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=30),
        ),
    ]
