# Generated by Django 2.0.3 on 2018-04-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20180401_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='caseworker',
        ),
        migrations.AddField(
            model_name='case',
            name='caseworkers',
            field=models.ManyToManyField(blank=True, to='cases.Person'),
        ),
    ]
