# Generated by Django 2.0.3 on 2018-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
