# Generated by Django 2.0.3 on 2018-03-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
