# Generated by Django 2.0.4 on 2018-04-12 08:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20180406_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='division',
            new_name='divisions',
        ),
        migrations.RemoveField(
            model_name='case',
            name='division',
        ),
        migrations.AddField(
            model_name='case',
            name='divisions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], max_length=15),
        ),
    ]
