# Generated by Django 2.1.3 on 2018-11-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20181119_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['value']},
        ),
        migrations.AlterField(
            model_name='case',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_cases', to='cases.Tag', verbose_name='How did the client hear about the office?'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='acronym',
            field=models.CharField(blank=True, help_text="Common acronym/abbreviation for this tag, if it has one (e.g. 'CSC' )", max_length=10),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(help_text="Full name of the thing this tag is labelling (e.g. 'Center for Student Conduct')", max_length=50),
        ),
    ]
