# Generated by Django 2.0.3 on 2018-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20180329_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=30),
        ),
    ]
