# Generated by Django 2.1.3 on 2018-12-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20181121_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='acronym',
            field=models.CharField(blank=True, help_text="Common acronym/abbreviation for this tag, if it has one (e.g. 'CSC' )", max_length=20),
        ),
    ]
