# Generated by Django 2.0.4 on 2018-04-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20180412_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='divisions',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='divisions',
            new_name='division',
        ),
    ]
