# Generated by Django 2.0.4 on 2018-04-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20180412_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='division',
            new_name='divisions',
        ),
    ]
