# Generated by Django 2.1.5 on 2019-04-12 21:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20181204_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='divisions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], default='ACA', max_length=15),
            preserve_default=False,
        ),
    ]
