# Generated by Django 2.0.4 on 2018-04-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20180412_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='slug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
