# Generated by Django 2.0.4 on 2018-04-22 04:25

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client_SID',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='case',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='date case was closed'),
        ),
        migrations.AlterField(
            model_name='case',
            name='divisions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ACA', 'Academic'), ('GRI', 'Grievance'), ('FIN', 'Financial Aid'), ('CON', 'Conduct')], max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='incident_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
