# Generated by Django 2.0.3 on 2018-03-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20180329_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
