# Generated by Django 2.0.4 on 2018-04-22 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_auto_20180421_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('update_description', models.TextField()),
            ],
        ),
    ]
