# Generated by Django 2.0.4 on 2018-04-22 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_caseupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseupdate',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
