# Generated by Django 2.0.4 on 2018-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_caseupdate_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseupdate',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
