# Generated by Django 2.0.4 on 2018-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_auto_20180422_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name'], 'verbose_name': 'Caseworker'},
        ),
    ]
