# Generated by Django 2.0.5 on 2018-05-27 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_auto_20180525_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['last_updated']},
        ),
        migrations.AddField(
            model_name='case',
            name='last_updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='time since last update'),
            preserve_default=False,
        ),
    ]
