# Generated by Django 2.0.5 on 2018-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20180526_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time since last update'),
        ),
    ]
