# Generated by Django 2.0.5 on 2018-05-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20180526_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-last_updated']},
        ),
    ]
