# Generated by Django 2.0.5 on 2018-05-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20180526_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='isOpen',
            new_name='is_open',
        ),
    ]
