# Generated by Django 2.0.5 on 2018-05-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_remove_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='slug',
        ),
    ]
