# Generated by Django 2.0.6 on 2018-07-25 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_remove_case_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='open_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date case was opened'),
        ),
    ]
